"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Counter__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Counter__factory_1 = require("./Counter__factory");
Object.defineProperty(exports, "Counter__factory", { enumerable: true, get: function () { return Counter__factory_1.Counter__factory; } });
